### ISSUE TITLE
2D vs 3D, literature refs

### ISSUE THREAD

**Issue by SimonEnsemble** [core-cof/CoRE-COF-Database#1]
Hi,

Very nice work! I hope @gregchung is aware of your database.

In your database, is there a straightforward way for me to distinguish between 2D and 3D COFs? I notice that the 2D COFs have a small `c` unit cell parameter, so I suppose I could filter on that.

Also, do you have a list that maps each COF structure to a DOI for the paper in which it was reported? That would be very helpful.

Thank you.

**Comment by core-cof** [comment]
Hi,
Simon.
Thank you for your attention. In the present database, the 2D and 3D COFs are not classified. Yes, they can be distinguished by the parameters of unit cell, but not only confined to c axis, sometimes the a or b unit cell is the short one.  The database will be updated recently, and with your helpful suggestion, I'll  mark them with 2D or 3D  and with the exp published reference.

**Comment by SimonEnsemble** [comment]
Hi! I saw that a new version was posted!
I think your work would have a much greater impact if you could provide the literature references to each COF in this database. That way, one can look up the experimental protocols for synthesizing the given COF. Is there any way I can see which COF links to which DOI reference? Thank you!

**Comment by SimonEnsemble** [comment]
Ah, I see the first line has the COF names! That is quite helpful!

Now, e.g. to find CTF-1, I can do:
```
grep "CTF-1" *
```
and I see 73.cif is CTF-1.

It still would be fantastic to have the DOI associated with each COF as well as whether they are 2D or 3D.

Thank you for your great work on compiling this database!

**Comment by core-cof** [comment]
Hi, Simon, thank you for you attention. I have uploaded a .xslx file about the detailed information of the structures. Please check it.



tongmm@jsnu.edu.cn
 
From: Cory Simon
Date: 2018-01-25 08:34
To: core-cof/CoRE-COF-Database
CC: Shared Collected Experimental COFs; Comment
Subject: Re: [core-cof/CoRE-COF-Database] 2D vs 3D, literature refs (#1)
Hi! I saw that a new version was posted!
I think your work would have a much greater impact if you could provide the literature references to each COF in this database. That way, one can look up the experimental protocols for synthesizing the given COF. Is there any way I can see which COF links to which DOI reference? Thank you!

**Comment by SimonEnsemble** [comment]
Excellent, thank you! 
🎉
